#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
cookbook 'runit'
cookbook 'nginx', git: 'git://github.com/opscode-cookbooks/nginx.git'

cookbook "user", git: "https://github.com/fnichol/chef-user"

cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
